title: "lowpoly by paz"

theme: minima

author:
  name: Alexander Paz
  short_name: '@alexjpaz'
  email: "alex.j.paz@gmail.com"
  website: "https://alexjpaz.com"

github_url: "https://github.com/alexjpaz/lowpoly"
